# Generated by Django 3.0.5 on 2020-04-16 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Time of created')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Time of last update')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Time then row was deleted')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted row')),
                ('name', models.CharField(max_length=225, verbose_name='Title')),
                ('db_file', models.FileField(upload_to='videos/')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
