# Generated by Django 3.0.5 on 2020-04-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200417_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='height',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='width',
        ),
    ]
