# Generated by Django 3.0.5 on 2020-04-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200417_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
